#!/usr/bin/env node
var path = require('path')
var lib = require(path.join(__dirname, '../utilities/browser-run/lib.js'))
lib.start('/Applications/Google\\ Chrome.app/Contents/MacOS/Google\\ Chrome')
