SHELL := /bin/bash

build: build/c build/asmjs build/opencl build/webcl

build/c:
	mkdir -p build/c

build/asmjs:
	mkdir -p build/asmjs

build/js:
	mkdir -p build/js

build/opencl:
	mkdir -p build/opencl

build/webcl:
	mkdir -p build/webcl

clean:
	rm -rf build
