#!/usr/bin/env python
import argparse
import sys
import subprocess


parser = argparse.ArgumentParser(description='Unified interface for running Matlab programs on the command line.')
parser.add_argument('function', type=str, 
                   help='the name of the matlab function to call first')
parser.add_argument('arguments', metavar='A', nargs='*', type=str,
				   help='positional arguments to pass to the virtual machine')

args = parser.parse_args()

matlab_runner_script = """try %s(%s); exit(0); catch, ME = lasterror; fprintf(2, '%%s\\n', ME.message); exit(1); end"""

try:
	subprocess.check_call(
		['matlab', 
			'-nodesktop', 
			'-nodisplay', 
			'-r', 
			matlab_runner_script%(args.function,','.join(args.arguments))
		], stdout=sys.stdout, stderr=sys.stderr)
	sys.exit(0)
except subprocess.CalledProcessError as e:
	sys.exit(e.returncode)











